-- Kyndryl Rally - Database Schema
-- Run this script in MySQL to create the database and tables

CREATE DATABASE IF NOT EXISTS kyndryl_rally CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kyndryl_rally;

-- Participants table
CREATE TABLE IF NOT EXISTS participants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) UNIQUE NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  empresa VARCHAR(150) DEFAULT '',
  puesto VARCHAR(150) DEFAULT '',
  telefono VARCHAR(30) DEFAULT '',
  ciudad VARCHAR(100) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Stage progress tracking
CREATE TABLE IF NOT EXISTS stage_progress (
  id INT AUTO_INCREMENT PRIMARY KEY,
  participant_id INT NOT NULL,
  stage_number TINYINT NOT NULL,
  completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_by VARCHAR(50) DEFAULT 'self',
  FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE,
  UNIQUE KEY unique_stage (participant_id, stage_number)
) ENGINE=InnoDB;

-- Generated images
CREATE TABLE IF NOT EXISTS generated_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  participant_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  download_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Swag vouchers
CREATE TABLE IF NOT EXISTS swag_vouchers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  participant_id INT NOT NULL,
  voucher_code VARCHAR(20) UNIQUE NOT NULL,
  swag_item VARCHAR(100) NOT NULL,
  redeemed BOOLEAN DEFAULT FALSE,
  redeemed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Staff users
CREATE TABLE IF NOT EXISTS staff_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('staff', 'admin') DEFAULT 'staff',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Insert default admin user (password: admin123 - CHANGE IN PRODUCTION)
-- The hash will be generated by the seed script
